/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotto2;

/**
 *
 * @author Paul
 */
public class homeScreenGUI extends javax.swing.JFrame {

    /**
     * Creates new form resultGUI
     */
    public homeScreenGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rBgArea = new javax.swing.JPanel();
        logoLbl = new javax.swing.JLabel();
        lottoBallsLbl = new javax.swing.JLabel();
        HotpicksLbl = new javax.swing.JLabel();
        playLottoBtn = new javax.swing.JButton();
        playLottoPlusBtn = new javax.swing.JButton();
        saveLbl = new javax.swing.JLabel();
        saveIcon = new javax.swing.JLabel();
        viewLbl = new javax.swing.JLabel();
        viewIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 240));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(650, 100));
        setSize(new java.awt.Dimension(682, 829));

        rBgArea.setBackground(new java.awt.Color(102, 204, 255));
        rBgArea.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 0, 0)));

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/lotto.jpg"))); // NOI18N

        lottoBallsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/lottoballs.png"))); // NOI18N

        HotpicksLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/lotto.png"))); // NOI18N
        HotpicksLbl.setText("jLabel1");

        playLottoBtn.setBackground(new java.awt.Color(102, 204, 255));
        playLottoBtn.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        playLottoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/lottoball1.png"))); // NOI18N
        playLottoBtn.setBorder(null);
        playLottoBtn.setBorderPainted(false);
        playLottoBtn.setContentAreaFilled(false);
        playLottoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playLottoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playLottoBtnActionPerformed(evt);
            }
        });

        playLottoPlusBtn.setBackground(new java.awt.Color(102, 204, 255));
        playLottoPlusBtn.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        playLottoPlusBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/lottoball2.png"))); // NOI18N
        playLottoPlusBtn.setBorder(null);
        playLottoPlusBtn.setContentAreaFilled(false);
        playLottoPlusBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playLottoPlusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playLottoPlusBtnActionPerformed(evt);
            }
        });

        saveLbl.setBackground(new java.awt.Color(102, 204, 240));
        saveLbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        saveLbl.setForeground(new java.awt.Color(255, 255, 255));
        saveLbl.setText("Save");

        saveIcon.setBackground(new java.awt.Color(102, 204, 255));
        saveIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/save-icon-2.png"))); // NOI18N

        viewLbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        viewLbl.setForeground(new java.awt.Color(255, 255, 255));
        viewLbl.setText("View");

        viewIcon.setBackground(new java.awt.Color(102, 204, 240));
        viewIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/view.png"))); // NOI18N

        javax.swing.GroupLayout rBgAreaLayout = new javax.swing.GroupLayout(rBgArea);
        rBgArea.setLayout(rBgAreaLayout);
        rBgAreaLayout.setHorizontalGroup(
            rBgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rBgAreaLayout.createSequentialGroup()
                .addGroup(rBgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rBgAreaLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(logoLbl))
                    .addGroup(rBgAreaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(saveLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveIcon))
                    .addGroup(rBgAreaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(viewLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewIcon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rBgAreaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rBgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rBgAreaLayout.createSequentialGroup()
                        .addComponent(playLottoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playLottoPlusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rBgAreaLayout.createSequentialGroup()
                        .addComponent(HotpicksLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(lottoBallsLbl)))
                .addGap(174, 174, 174))
        );
        rBgAreaLayout.setVerticalGroup(
            rBgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rBgAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rBgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rBgAreaLayout.createSequentialGroup()
                        .addGroup(rBgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveIcon)
                            .addComponent(saveLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewLbl)
                        .addGap(7, 7, 7))
                    .addComponent(viewIcon))
                .addGap(1, 1, 1)
                .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rBgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playLottoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playLottoPlusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(rBgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lottoBallsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HotpicksLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rBgArea, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rBgArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playLottoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playLottoBtnActionPerformed
        // TODO add your handling code here:
        homeScreenGUI first = new homeScreenGUI();
        first.setVisible(false);
        dispose();
        lottoGameOneGUI second = new lottoGameOneGUI();
        second.setVisible(true);
    }//GEN-LAST:event_playLottoBtnActionPerformed

    private void playLottoPlusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playLottoPlusBtnActionPerformed
        // TODO add your handling code here:
        homeScreenGUI first = new homeScreenGUI();
        first.setVisible(false);
        dispose();
        lottoGUI second = new lottoGUI();
        second.setVisible(true);
    }//GEN-LAST:event_playLottoPlusBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeScreenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeScreenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeScreenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeScreenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeScreenGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HotpicksLbl;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JLabel lottoBallsLbl;
    private javax.swing.JButton playLottoBtn;
    private javax.swing.JButton playLottoPlusBtn;
    private javax.swing.JPanel rBgArea;
    private javax.swing.JLabel saveIcon;
    private javax.swing.JLabel saveLbl;
    private javax.swing.JLabel viewIcon;
    private javax.swing.JLabel viewLbl;
    // End of variables declaration//GEN-END:variables
}
