/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotto2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author x13125974
 */
public class lottoGameOneGUI extends javax.swing.JFrame {

    int[] savedNums = new int[5];
    int[] savedNumsLine2 = new int[5];
    int[] savedNumsLine3 = new int[5];
    int[][] lotto = new int[3][5];
    int[] winningNum = new int[5];
    int line1 = 0;
    int line2 = 0;
    int line3 = 0;

    public void randomNum() {
        //generating 5 randon numbers between 1 - 40 and storing them in the array called "winningNum this also excludes numbers below 1 and above 40"
        for (int i = 0; i < winningNum.length; i++) {
            winningNum[i] = (int) Math.floor(1 + Math.random() * 40);

            // prints the 5 random numbers to the console
            System.out.println(winningNum[i]);
        }

    }

    public void compute() {
        for (int i = 0; i < 1; i++) {
            for (int j = 0; j < 5; j++) {
                //  comparring arrays for counting number of succesfull tries per line
                if (winningNum[j] == lotto[i][0] || winningNum[j] == lotto[i][1] || winningNum[j] == lotto[i][2] || winningNum[j] == lotto[i][3] || winningNum[j] == lotto[i][4]) {
                    line1++;

                }

            }
        }
        //2nd loop for 2nd user input for line 2
        for (int i = 1; i < 2; i++) {
            for (int j = 0; j < 5; j++) {

                //validation - prevents user from inputting an invalid number
                if (lotto[i][j] > 40 || lotto[i][j] < 1) {

                    i = -1;
                    break;
                }

                //comparring arrays for counting number of succesfull tries per line
                if (winningNum[j] == lotto[i][0] || winningNum[j] == lotto[i][1] || winningNum[j] == lotto[i][2] || winningNum[j] == lotto[1][3] || winningNum[j] == lotto[i][4]) {
                    line2++;

                }

            }

        }
        for (int i = 2; i < lotto.length; i++) {
            for (int j = 0; j < 5; j++) {
                //comparring arrays for counting number of succesfull tries per line
                if (winningNum[j] == lotto[i][0] || winningNum[j] == lotto[i][1] || winningNum[j] == lotto[i][2] || winningNum[j] == lotto[1][3] || winningNum[j] == lotto[i][4]) {
                    line3++;

                }

            }
        }
    }

    /**
     * Creates new form lottoGameOneGUI
     */
    public lottoGameOneGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        G1BgArea = new javax.swing.JPanel();
        enetrNumsLbl = new javax.swing.JLabel();
        line1Lbl = new javax.swing.JLabel();
        line2Lbl = new javax.swing.JLabel();
        line3Lbl = new javax.swing.JLabel();
        line1Input1TF = new javax.swing.JTextField();
        line1Input2TF = new javax.swing.JTextField();
        line1Input3TF = new javax.swing.JTextField();
        line1Input4TF = new javax.swing.JTextField();
        line1Input5TF = new javax.swing.JTextField();
        line2Input1TF = new javax.swing.JTextField();
        line2Input2TF = new javax.swing.JTextField();
        line2Input3TF = new javax.swing.JTextField();
        line2Input4TF = new javax.swing.JTextField();
        line2Input5TF = new javax.swing.JTextField();
        line3Input1TF = new javax.swing.JTextField();
        line3Input2TF = new javax.swing.JTextField();
        line3Input3TF = new javax.swing.JTextField();
        line3Input4TF = new javax.swing.JTextField();
        line3Input5TF = new javax.swing.JTextField();
        PlayBtn = new javax.swing.JButton();
        logoLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Rline1 = new javax.swing.JLabel();
        Rline2 = new javax.swing.JLabel();
        Rline3 = new javax.swing.JLabel();
        Rline1TF = new javax.swing.JTextField();
        Rline2TF = new javax.swing.JTextField();
        Rline3TF = new javax.swing.JTextField();
        matchsLbl = new javax.swing.JLabel();
        resultLbl = new javax.swing.JLabel();
        winningNumsTF = new javax.swing.JTextField();
        homeIconLbl = new javax.swing.JButton();
        saveLineLbl = new javax.swing.JButton();
        saveLine2 = new javax.swing.JButton();
        saveLine3Btn = new javax.swing.JButton();
        viewLine1Btn = new javax.swing.JButton();
        viewLine2Btn = new javax.swing.JButton();
        viewLine3Btn = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(650, 100));
        setSize(new java.awt.Dimension(682, 829));

        G1BgArea.setBackground(new java.awt.Color(102, 204, 255));
        G1BgArea.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 0, 0)));

        enetrNumsLbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        enetrNumsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/lotto.jpg"))); // NOI18N

        line1Lbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line1Lbl.setForeground(new java.awt.Color(255, 255, 255));
        line1Lbl.setText("Line1:");

        line2Lbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line2Lbl.setForeground(new java.awt.Color(255, 255, 255));
        line2Lbl.setText("Line2:");

        line3Lbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line3Lbl.setForeground(new java.awt.Color(255, 255, 255));
        line3Lbl.setText("Line3:");

        line1Input1TF.setBackground(new java.awt.Color(255, 255, 0));
        line1Input1TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line1Input1TF.setForeground(new java.awt.Color(255, 0, 0));
        line1Input1TF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        line1Input1TF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        line1Input1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line1Input1TFActionPerformed(evt);
            }
        });

        line1Input2TF.setBackground(new java.awt.Color(255, 255, 0));
        line1Input2TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line1Input2TF.setForeground(new java.awt.Color(255, 0, 0));
        line1Input2TF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        line1Input2TF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        line1Input2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line1Input2TFActionPerformed(evt);
            }
        });

        line1Input3TF.setBackground(new java.awt.Color(255, 255, 0));
        line1Input3TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line1Input3TF.setForeground(new java.awt.Color(255, 0, 0));
        line1Input3TF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        line1Input3TF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        line1Input3TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line1Input3TFActionPerformed(evt);
            }
        });

        line1Input4TF.setBackground(new java.awt.Color(255, 255, 0));
        line1Input4TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line1Input4TF.setForeground(new java.awt.Color(255, 0, 0));
        line1Input4TF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        line1Input4TF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        line1Input4TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line1Input4TFActionPerformed(evt);
            }
        });

        line1Input5TF.setBackground(new java.awt.Color(255, 255, 0));
        line1Input5TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line1Input5TF.setForeground(new java.awt.Color(255, 0, 0));
        line1Input5TF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        line1Input5TF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        line1Input5TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line1Input5TFActionPerformed(evt);
            }
        });

        line2Input1TF.setBackground(new java.awt.Color(255, 255, 0));
        line2Input1TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line2Input1TF.setForeground(new java.awt.Color(255, 0, 0));
        line2Input1TF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        line2Input1TF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        line2Input1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line2Input1TFActionPerformed(evt);
            }
        });

        line2Input2TF.setBackground(new java.awt.Color(255, 255, 0));
        line2Input2TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line2Input2TF.setForeground(new java.awt.Color(255, 0, 0));
        line2Input2TF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        line2Input2TF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        line2Input2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line2Input2TFActionPerformed(evt);
            }
        });

        line2Input3TF.setBackground(new java.awt.Color(255, 255, 0));
        line2Input3TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line2Input3TF.setForeground(new java.awt.Color(255, 0, 0));
        line2Input3TF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        line2Input3TF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        line2Input3TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line2Input3TFActionPerformed(evt);
            }
        });

        line2Input4TF.setBackground(new java.awt.Color(255, 255, 0));
        line2Input4TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line2Input4TF.setForeground(new java.awt.Color(255, 0, 0));
        line2Input4TF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        line2Input4TF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        line2Input4TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line2Input4TFActionPerformed(evt);
            }
        });

        line2Input5TF.setBackground(new java.awt.Color(255, 255, 0));
        line2Input5TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line2Input5TF.setForeground(new java.awt.Color(255, 0, 0));
        line2Input5TF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        line2Input5TF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        line2Input5TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line2Input5TFActionPerformed(evt);
            }
        });

        line3Input1TF.setBackground(new java.awt.Color(255, 255, 0));
        line3Input1TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line3Input1TF.setForeground(new java.awt.Color(255, 0, 0));
        line3Input1TF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        line3Input1TF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        line3Input1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line3Input1TFActionPerformed(evt);
            }
        });

        line3Input2TF.setBackground(new java.awt.Color(255, 255, 0));
        line3Input2TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line3Input2TF.setForeground(new java.awt.Color(255, 0, 0));
        line3Input2TF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        line3Input2TF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        line3Input2TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line3Input2TFActionPerformed(evt);
            }
        });

        line3Input3TF.setBackground(new java.awt.Color(255, 255, 0));
        line3Input3TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line3Input3TF.setForeground(new java.awt.Color(255, 0, 0));
        line3Input3TF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        line3Input3TF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        line3Input3TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line3Input3TFActionPerformed(evt);
            }
        });

        line3Input4TF.setBackground(new java.awt.Color(255, 255, 0));
        line3Input4TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line3Input4TF.setForeground(new java.awt.Color(255, 0, 0));
        line3Input4TF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        line3Input4TF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        line3Input4TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line3Input4TFActionPerformed(evt);
            }
        });

        line3Input5TF.setBackground(new java.awt.Color(255, 255, 0));
        line3Input5TF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        line3Input5TF.setForeground(new java.awt.Color(255, 0, 0));
        line3Input5TF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        line3Input5TF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        line3Input5TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                line3Input5TFActionPerformed(evt);
            }
        });

        PlayBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/howtoplay1.png"))); // NOI18N
        PlayBtn.setBorderPainted(false);
        PlayBtn.setContentAreaFilled(false);
        PlayBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PlayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayBtnActionPerformed(evt);
            }
        });

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/lotto.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        Rline1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Rline1.setForeground(new java.awt.Color(255, 255, 255));
        Rline1.setText("Line1:");

        Rline2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Rline2.setForeground(new java.awt.Color(255, 255, 255));
        Rline2.setText("Line2:");

        Rline3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Rline3.setForeground(new java.awt.Color(255, 255, 255));
        Rline3.setText("Line3:");

        Rline1TF.setBackground(new java.awt.Color(102, 204, 255));
        Rline1TF.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Rline1TF.setForeground(new java.awt.Color(255, 255, 255));
        Rline1TF.setBorder(null);

        Rline2TF.setBackground(new java.awt.Color(102, 204, 255));
        Rline2TF.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Rline2TF.setForeground(new java.awt.Color(255, 255, 255));
        Rline2TF.setBorder(null);

        Rline3TF.setBackground(new java.awt.Color(102, 204, 255));
        Rline3TF.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Rline3TF.setForeground(new java.awt.Color(255, 255, 255));
        Rline3TF.setBorder(null);

        matchsLbl.setBackground(new java.awt.Color(102, 204, 240));
        matchsLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        matchsLbl.setForeground(new java.awt.Color(255, 255, 255));
        matchsLbl.setText("Matchs:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(matchsLbl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Rline2)
                                    .addComponent(Rline1))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Rline1TF, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                    .addComponent(Rline2TF)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Rline3)
                                .addGap(35, 35, 35)
                                .addComponent(Rline3TF)))
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(matchsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rline1)
                    .addComponent(Rline1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rline2)
                    .addComponent(Rline2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rline3)
                    .addComponent(Rline3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        resultLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        resultLbl.setForeground(new java.awt.Color(255, 255, 255));
        resultLbl.setText("Winning numbers are");

        winningNumsTF.setBackground(new java.awt.Color(255, 255, 0));
        winningNumsTF.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        winningNumsTF.setForeground(new java.awt.Color(255, 0, 0));
        winningNumsTF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        homeIconLbl.setBackground(new java.awt.Color(102, 204, 240));
        homeIconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/home-icon-4.png"))); // NOI18N
        homeIconLbl.setBorder(null);
        homeIconLbl.setBorderPainted(false);
        homeIconLbl.setContentAreaFilled(false);
        homeIconLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeIconLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeIconLblActionPerformed(evt);
            }
        });

        saveLineLbl.setBackground(new java.awt.Color(102, 204, 240));
        saveLineLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/save-icon-2.png"))); // NOI18N
        saveLineLbl.setBorder(null);
        saveLineLbl.setBorderPainted(false);
        saveLineLbl.setContentAreaFilled(false);
        saveLineLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveLineLbl.setFocusPainted(false);
        saveLineLbl.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/valid-512.png"))); // NOI18N
        saveLineLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveLineLblActionPerformed(evt);
            }
        });

        saveLine2.setBackground(new java.awt.Color(102, 204, 240));
        saveLine2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/save-icon-2.png"))); // NOI18N
        saveLine2.setBorder(null);
        saveLine2.setBorderPainted(false);
        saveLine2.setContentAreaFilled(false);
        saveLine2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveLine2.setFocusPainted(false);
        saveLine2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/valid-512.png"))); // NOI18N
        saveLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveLine2ActionPerformed(evt);
            }
        });

        saveLine3Btn.setBackground(new java.awt.Color(102, 204, 240));
        saveLine3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/save-icon-2.png"))); // NOI18N
        saveLine3Btn.setBorder(null);
        saveLine3Btn.setBorderPainted(false);
        saveLine3Btn.setContentAreaFilled(false);
        saveLine3Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveLine3Btn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/valid-512.png"))); // NOI18N
        saveLine3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveLine3BtnActionPerformed(evt);
            }
        });

        viewLine1Btn.setBackground(new java.awt.Color(102, 204, 240));
        viewLine1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/view.png"))); // NOI18N
        viewLine1Btn.setBorder(null);
        viewLine1Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewLine1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLine1BtnActionPerformed(evt);
            }
        });

        viewLine2Btn.setBackground(new java.awt.Color(102, 204, 240));
        viewLine2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/view.png"))); // NOI18N
        viewLine2Btn.setBorder(null);
        viewLine2Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewLine2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLine2BtnActionPerformed(evt);
            }
        });

        viewLine3Btn.setBackground(new java.awt.Color(102, 204, 240));
        viewLine3Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lotto2/view.png"))); // NOI18N
        viewLine3Btn.setBorder(null);
        viewLine3Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewLine3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLine3BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout G1BgAreaLayout = new javax.swing.GroupLayout(G1BgArea);
        G1BgArea.setLayout(G1BgAreaLayout);
        G1BgAreaLayout.setHorizontalGroup(
            G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(G1BgAreaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(G1BgAreaLayout.createSequentialGroup()
                        .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(line1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(line2Lbl))
                            .addComponent(line3Lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewLine1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(viewLine2Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewLine3Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(G1BgAreaLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enetrNumsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, G1BgAreaLayout.createSequentialGroup()
                                        .addComponent(PlayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))))
                            .addGroup(G1BgAreaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(G1BgAreaLayout.createSequentialGroup()
                                        .addComponent(line1Input1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line1Input2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line1Input3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line1Input4TF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line1Input5TF, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(G1BgAreaLayout.createSequentialGroup()
                                        .addComponent(line3Input1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line3Input2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line3Input3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line3Input4TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line3Input5TF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(G1BgAreaLayout.createSequentialGroup()
                                        .addComponent(line2Input1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line2Input2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line2Input3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line2Input4TF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(line2Input5TF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saveLine3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(saveLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(saveLineLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, G1BgAreaLayout.createSequentialGroup()
                        .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(G1BgAreaLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resultLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(G1BgAreaLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(homeIconLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(G1BgAreaLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(winningNumsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))))
        );

        G1BgAreaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {line1Input1TF, line1Input2TF, line1Input3TF, line1Input4TF, line1Input5TF, line2Input1TF, line2Input2TF, line2Input3TF, line2Input4TF, line2Input5TF, line3Input1TF, line3Input2TF, line3Input3TF, line3Input4TF, line3Input5TF});

        G1BgAreaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {line1Lbl, line2Lbl, line3Lbl});

        G1BgAreaLayout.setVerticalGroup(
            G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, G1BgAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enetrNumsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(G1BgAreaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(line1Lbl)
                            .addComponent(viewLine1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(line2Lbl)
                            .addComponent(viewLine2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewLine3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(line3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, G1BgAreaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveLineLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(line1Input3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(line1Input4TF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(line1Input5TF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(line1Input1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(line1Input2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(G1BgAreaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(line2Input1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(line2Input3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(line2Input4TF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(line2Input5TF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(line2Input2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, G1BgAreaLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(saveLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(line3Input1TF)
                            .addComponent(line3Input2TF)
                            .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(line3Input3TF)
                                .addComponent(line3Input4TF)
                                .addComponent(line3Input5TF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(saveLine3Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(G1BgAreaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 441, Short.MAX_VALUE)
                        .addComponent(homeIconLbl))
                    .addGroup(G1BgAreaLayout.createSequentialGroup()
                        .addComponent(PlayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(G1BgAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(G1BgAreaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(resultLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(G1BgAreaLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(winningNumsTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        G1BgAreaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {line1Input1TF, line1Input2TF, line1Input3TF, line1Input4TF, line1Input5TF, line2Input1TF, line2Input2TF, line2Input3TF, line2Input4TF, line2Input5TF, line3Input1TF, line3Input2TF, line3Input3TF, line3Input4TF, line3Input5TF});

        G1BgAreaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {line1Lbl, line2Lbl, line3Lbl});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(G1BgArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(G1BgArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void line1Input1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line1Input1TFActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_line1Input1TFActionPerformed

    private void line2Input4TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line2Input4TFActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_line2Input4TFActionPerformed

    private void line1Input2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line1Input2TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_line1Input2TFActionPerformed

    private void line1Input3TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line1Input3TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_line1Input3TFActionPerformed

    private void line1Input4TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line1Input4TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_line1Input4TFActionPerformed

    private void line1Input5TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line1Input5TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_line1Input5TFActionPerformed

    private void line2Input1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line2Input1TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_line2Input1TFActionPerformed

    private void line2Input2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line2Input2TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_line2Input2TFActionPerformed

    private void line2Input3TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line2Input3TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_line2Input3TFActionPerformed

    private void line2Input5TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line2Input5TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_line2Input5TFActionPerformed

    private void line3Input1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line3Input1TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_line3Input1TFActionPerformed

    private void line3Input2TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line3Input2TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_line3Input2TFActionPerformed

    private void line3Input3TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line3Input3TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_line3Input3TFActionPerformed

    private void line3Input4TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line3Input4TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_line3Input4TFActionPerformed

    private void line3Input5TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_line3Input5TFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_line3Input5TFActionPerformed

    private void PlayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayBtnActionPerformed
        // TODO add your handling code here:
        randomNum();
        lotto[0][0] = Integer.parseInt(line1Input1TF.getText());
        lotto[0][1] = Integer.parseInt(line1Input2TF.getText());
        lotto[0][2] = Integer.parseInt(line1Input3TF.getText());
        lotto[0][3] = Integer.parseInt(line1Input4TF.getText());
        lotto[0][4] = Integer.parseInt(line1Input5TF.getText());
        lotto[1][0] = Integer.parseInt(line2Input1TF.getText());
        lotto[1][1] = Integer.parseInt(line2Input2TF.getText());
        lotto[1][2] = Integer.parseInt(line2Input3TF.getText());
        lotto[1][3] = Integer.parseInt(line2Input4TF.getText());
        lotto[1][4] = Integer.parseInt(line2Input5TF.getText());
        lotto[2][0] = Integer.parseInt(line3Input1TF.getText());
        lotto[2][1] = Integer.parseInt(line3Input2TF.getText());
        lotto[2][2] = Integer.parseInt(line3Input3TF.getText());
        lotto[2][3] = Integer.parseInt(line3Input4TF.getText());
        lotto[2][4] = Integer.parseInt(line3Input5TF.getText());
        compute();

        Rline1TF.setText(Integer.toString(line1));
        Rline2TF.setText(Integer.toString(line2));
        Rline3TF.setText(Integer.toString(line3));
        winningNumsTF.setText(Arrays.toString(winningNum));


    }//GEN-LAST:event_PlayBtnActionPerformed

    private void homeIconLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeIconLblActionPerformed
        // TODO add your handling code here:
        lottoGameOneGUI first = new lottoGameOneGUI();
        first.setVisible(false);
        dispose();
        homeScreenGUI second = new homeScreenGUI();
        second.setVisible(true);
    }//GEN-LAST:event_homeIconLblActionPerformed

    private void saveLineLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveLineLblActionPerformed
        // TODO add your handling code here:
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        savedNums[0] = Integer.parseInt(line1Input1TF.getText());
        savedNums[1] = Integer.parseInt(line1Input2TF.getText());
        savedNums[2] = Integer.parseInt(line1Input3TF.getText());
        savedNums[3] = Integer.parseInt(line1Input4TF.getText());
        savedNums[4] = Integer.parseInt(line1Input5TF.getText());

        try {
            outFile = new File("line1.txt");
            fw = new FileWriter(outFile);
            bw = new BufferedWriter(fw);

            for (int i = 0; i < savedNums.length; i++) {
                bw.write(Integer.toString(savedNums[i]));

                bw.newLine();

                System.out.println(savedNums[i]);
            }

            bw.close();
            JOptionPane.showMessageDialog(null, "Line1 saved (Numbers also saved for mainLotto game type)");
        } catch (IOException e) {
            System.out.println("error" + e);

        }
    }//GEN-LAST:event_saveLineLblActionPerformed

    private void saveLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveLine2ActionPerformed
        // TODO add your handling code here:
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        savedNumsLine2[0] = Integer.parseInt(line2Input1TF.getText());
        savedNumsLine2[1] = Integer.parseInt(line2Input2TF.getText());
        savedNumsLine2[2] = Integer.parseInt(line2Input3TF.getText());
        savedNumsLine2[3] = Integer.parseInt(line2Input4TF.getText());
        savedNumsLine2[4] = Integer.parseInt(line2Input5TF.getText());

        try {
            outFile = new File("line2.txt");
            fw = new FileWriter(outFile);
            bw = new BufferedWriter(fw);

            for (int i = 0; i < savedNumsLine2.length; i++) {
                bw.write(Integer.toString(savedNumsLine2[i]));

                bw.newLine();

                System.out.println(savedNumsLine2[i]);
            }

            bw.close();
            JOptionPane.showMessageDialog(null, "Line2 saved (Numbers also saved for mainLotto game type)");
        } catch (IOException e) {
            System.out.println("error" + e);

        }
    }//GEN-LAST:event_saveLine2ActionPerformed

    private void saveLine3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveLine3BtnActionPerformed
        // TODO add your handling code here:
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        savedNumsLine3[0] = Integer.parseInt(line3Input1TF.getText());
        savedNumsLine3[1] = Integer.parseInt(line3Input2TF.getText());
        savedNumsLine3[2] = Integer.parseInt(line3Input3TF.getText());
        savedNumsLine3[3] = Integer.parseInt(line3Input4TF.getText());
        savedNumsLine3[4] = Integer.parseInt(line3Input5TF.getText());

        try {
            outFile = new File("line3.txt");
            fw = new FileWriter(outFile);
            bw = new BufferedWriter(fw);

            for (int i = 0; i < savedNumsLine3.length; i++) {
                bw.write(Integer.toString(savedNumsLine3[i]));

                bw.newLine();

                System.out.println(savedNumsLine3[i]);
            }

            bw.close();
            JOptionPane.showMessageDialog(null, "Line3 saved (Numbers are also saved for lottoPlus2 game type)");
        } catch (IOException e) {
            System.out.println("error" + e);

        }
    }//GEN-LAST:event_saveLine3BtnActionPerformed

    private void viewLine1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLine1BtnActionPerformed
        // TODO add your handling code here:

        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("line1.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            for (int i = 0; i < 5; i++) {
                savedNums[i] = Integer.parseInt(br.readLine());
            }

            line1Input1TF.setText(Integer.toString(savedNums[0]));
            line1Input2TF.setText(Integer.toString(savedNums[1]));
            line1Input3TF.setText(Integer.toString(savedNums[2]));
            line1Input4TF.setText(Integer.toString(savedNums[3]));
            line1Input5TF.setText(Integer.toString(savedNums[4]));
        } catch (IOException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_viewLine1BtnActionPerformed

    private void viewLine2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLine2BtnActionPerformed
        // TODO add your handling code here:

        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("line2.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            for (int i = 0; i < 5; i++) {
                savedNumsLine2[i] = Integer.parseInt(br.readLine());
            }

            line2Input1TF.setText(Integer.toString(savedNumsLine2[0]));
            line2Input2TF.setText(Integer.toString(savedNumsLine2[1]));
            line2Input3TF.setText(Integer.toString(savedNumsLine2[2]));
            line2Input4TF.setText(Integer.toString(savedNumsLine2[3]));
            line2Input5TF.setText(Integer.toString(savedNumsLine2[4]));
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_viewLine2BtnActionPerformed

    private void viewLine3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLine3BtnActionPerformed
        // TODO add your handling code here:

        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("line3.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            for (int i = 0; i < 5; i++) {
                savedNumsLine3[i] = Integer.parseInt(br.readLine());
            }

            line3Input1TF.setText(Integer.toString(savedNumsLine3[0]));
            line3Input2TF.setText(Integer.toString(savedNumsLine3[1]));
            line3Input3TF.setText(Integer.toString(savedNumsLine3[2]));
            line3Input4TF.setText(Integer.toString(savedNumsLine3[3]));
            line3Input5TF.setText(Integer.toString(savedNumsLine3[4]));
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_viewLine3BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lottoGameOneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lottoGameOneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lottoGameOneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lottoGameOneGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lottoGameOneGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel G1BgArea;
    private javax.swing.JButton PlayBtn;
    private javax.swing.JLabel Rline1;
    private javax.swing.JTextField Rline1TF;
    private javax.swing.JLabel Rline2;
    private javax.swing.JTextField Rline2TF;
    private javax.swing.JLabel Rline3;
    private javax.swing.JTextField Rline3TF;
    private javax.swing.JLabel enetrNumsLbl;
    private javax.swing.JButton homeIconLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField line1Input1TF;
    private javax.swing.JTextField line1Input2TF;
    private javax.swing.JTextField line1Input3TF;
    private javax.swing.JTextField line1Input4TF;
    private javax.swing.JTextField line1Input5TF;
    private javax.swing.JLabel line1Lbl;
    private javax.swing.JTextField line2Input1TF;
    private javax.swing.JTextField line2Input2TF;
    private javax.swing.JTextField line2Input3TF;
    private javax.swing.JTextField line2Input4TF;
    private javax.swing.JTextField line2Input5TF;
    private javax.swing.JLabel line2Lbl;
    private javax.swing.JTextField line3Input1TF;
    private javax.swing.JTextField line3Input2TF;
    private javax.swing.JTextField line3Input3TF;
    private javax.swing.JTextField line3Input4TF;
    private javax.swing.JTextField line3Input5TF;
    private javax.swing.JLabel line3Lbl;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JLabel matchsLbl;
    private javax.swing.JLabel resultLbl;
    private javax.swing.JButton saveLine2;
    private javax.swing.JButton saveLine3Btn;
    private javax.swing.JButton saveLineLbl;
    private javax.swing.JButton viewLine1Btn;
    private javax.swing.JButton viewLine2Btn;
    private javax.swing.JButton viewLine3Btn;
    private javax.swing.JTextField winningNumsTF;
    // End of variables declaration//GEN-END:variables
}
